proxy:
  title: Open Analytics Shiny Proxy
  logo-url: https://www.openanalytics.eu/shinyproxy/logo.png
  landing-page: /
  heartbeat-rate: 10000
  heartbeat-timeout: 60000
  port: 8080
  authentication: simple
  admin-groups: scientists
  # Example: 'simple' authentication configuration
  users:
  - name: jack
    password: password
    groups: scientists
  - name: jeff
    password: password
    groups: mathematicians
  # Docker configuration
  docker:
    internal-networking: true
  specs:
  - id: VisualizadorFallasET
    display-name: Visualizador de Fallas de ET
    description: Aplicación para el registro y análisis de fallas de ET
    container-cmd: ["R", "-e", "setwd('/usr/local/lib/R/site-library/VisualizadorFallasET');options('shiny.port'=3838,shiny.host='0.0.0.0');VisualizadorFallasET::run_app()"]
    container-image: epe/visualizadorfallas
    container-volumes: D:\OneDrive\OneDrive - frro.utn.edu.ar\Google Drive\UTN\PPS\Desarrollo\VisualizadorFallasET\shinyproxy\db\:/mnt/persistent
    container-network: epe-fallas-net
    access-groups: [scientists, mathematicians]
 

logging:
  file:
    name: shinyproxy.log