proxy:
  title: Visualizador de Fallas de EETT
  logo-url: https://www.epe.santafe.gov.ar/institucional/sites/default/files/logo-epe-blanco-nuevo.png
  landing-page: /app/VisualizadorFallasET
  heartbeat-rate: 10000
  heartbeat-timeout: 60000
  port: 8080
  authentication: simple
  admin-groups: admin
  users:
  - name: administrador
    password: Admin21&
    groups: admin
  - name: mantsur
    password: mantsur21
    groups: usuariosepe
  - name: mantnorte
    password: mantnorte21
    groups: usuariosepe
  # Docker configuration
  docker:
    internal-networking: true
  specs:
  - id: VisualizadorFallasET
    display-name: Visualizador de Fallas de ET
    description: Aplicación para el registro y análisis de fallas de ET
    container-cmd: ["R", "-e", "setwd('/usr/local/lib/R/site-library/VisualizadorFallasET');options('shiny.port'=3838,shiny.host='0.0.0.0');VisualizadorFallasET::run_app()"]
    container-image: epe/visualizadorfallas
    container-volumes: D:\OneDrive\OneDrive - frro.utn.edu.ar\Google Drive\UTN\PPS\Desarrollo\VisualizadorFallasET\shinyproxy\db\:/mnt/persistent
    container-network: epe-fallas-net
    access-groups: [usuariosepe, admin]
 

logging:
  file:
    name: shinyproxy.log